### ISSUE TITLE
Shared options>DMZ and/or should have explicit options for separate public and private address 

### ISSUE THREAD

**Issue by fititnt** [fititnt/ap-application-load-balancer#21]
The documentation of AP-ALB, as v0.8.0-alpha, have this on the Shared options: for the DMZ:

```yaml
alb_dmz:
 - ip: 203.0.113.1
   name: my_apps_server
 - ip: 203.0.113.2
   name: my_db_server
 - ip: 203.0.113.3
   name: any_other_server_inside_the_network
```

This is simple and works, but if we're about to implement #20, we will start to need some ways to at least specify public and private IPs.
