### ISSUE TITLE
HAProxy Stats Page as easy to configure option

### ISSUE THREAD

**Issue by fititnt** [fititnt/ap-application-load-balancer#7]
Allow (as option, not by default) HAProxy Stats Page https://www.haproxy.com/blog/exploring-the-haproxy-stats-page/.

This maybe also will be the start of have some types of apps that are mean to be for internal use, and not the `alb_apps` array

**Comment by fititnt** [comment]
ALB v0.5.0-alpha already have a MVP for implement HAProxy Status page.

Here some example of configuration

```yaml
- name: "ap-application-load-balancer playbook example (complex)"
  hosts: my_complex_hosts
  remote_user: root
  vars:
    alb_name: "MyALBName/2.0"
    alb_forcedebug: yes

    alb_haproxy_stats_enabled: yes

    alb_superuser_auth:
     - username: Admin1
       password: "plain-password"
     - username: Admin2
       password: "plain-password2"
    alb_superuser_ip: 123.123.123.123
    # alb_superuser_autodiscoveripnull: yes Not implemented yet
```

The passwords can be saved encrypted on yaml playbooks using Ansible Vault (see https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html) but the underline application still need plain passwords to work with less configurations
